package net.calvuz.qdue.core.domain.quattrodue.models;

import androidx.annotation.NonNull;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ✅ DOMAIN MODEL: Work Schedule Event
 *
 * <p>Represents a volatile work schedule event generated by WorkScheduleProvider
 * implementations. These events are temporary and generated on-demand based on
 * templates and patterns, similar to Google Calendar recurrence rules.</p>
 *
 * <p>Key characteristics:</p>
 * <ul>
 *   <li>Volatile - generated on-demand, not persisted</li>
 *   <li>Comparable with WorkScheduleException events for modifications</li>
 *   <li>Contains full temporal information (start/end times)</li>
 *   <li>Includes team assignments and shift details</li>
 *   <li>Trackable via composite identification</li>
 * </ul>
 *
 * @author Calendar App Team
 * @version 1.0
 * @since Database Version 5
 */
public class WorkScheduleEvent {

    // ==================== CORE IDENTIFICATION ====================

    private String volatileId;                    // Composite ID for tracking
    private String workScheduleTemplateId;        // Reference to generating template
    private int cycleDay;                         // Day within the rotation cycle

    // ==================== TEMPORAL INFORMATION ====================

    private LocalDate date;                       // Event date
    private LocalDateTime startDateTime;          // Full start date/time
    private LocalDateTime endDateTime;            // Full end date/time
    private boolean crossesMidnight;              // Flag for midnight crossing

    // ==================== WORK INFORMATION ====================

    private String title;                         // Display title
    private String description;                   // Detailed description
    private ShiftType shiftType;                  // Associated shift type
    private List<String> assignedTeams;           // Teams assigned to this event

    // ==================== METADATA ====================

    private boolean isRestPeriod;                 // Flag for rest periods
    private boolean isOvertime;                   // Flag for overtime events
    private String providerName;                  // Provider that generated this event
    private final long generatedTimestamp;              // When this event was generated

    // ==================== CONSTRUCTORS ====================

    /**
     * Default constructor for framework use.
     */
    public WorkScheduleEvent() {
        this.assignedTeams = new ArrayList<>();
        this.generatedTimestamp = System.currentTimeMillis();
    }

    /**
     * Primary constructor for creating work schedule events.
     *
     * @param title Event title
     * @param date Event date
     * @param shiftType Shift type for this event
     * @param assignedTeams Teams assigned to this shift
     */
    public WorkScheduleEvent(String title, LocalDate date, ShiftType shiftType, List<String> assignedTeams) {
        this();
        this.title = title;
        this.date = date;
        this.shiftType = shiftType;
        this.assignedTeams = assignedTeams != null ? new ArrayList<>(assignedTeams) : new ArrayList<>();

        // Calculate start/end times if shift type available
        if (shiftType != null && !shiftType.isRestPeriod()) {
            calculateDateTimes();
        }

        // Generate volatile ID
        this.volatileId = generateVolatileId();
    }

    // ==================== TEMPORAL CALCULATIONS ====================

    /**
     * Calculates full start and end date/time based on shift type and date.
     */
    private void calculateDateTimes() {
        if (date == null || shiftType == null || shiftType.isRestPeriod()) {
            return;
        }

        LocalTime startTime = shiftType.getStartTime();
        LocalTime endTime = shiftType.getEndTime();

        if (startTime != null && endTime != null) {
            this.startDateTime = date.atTime(startTime);

            // Handle midnight crossing
            if (endTime.isBefore(startTime)) {
                this.endDateTime = date.plusDays(1).atTime(endTime);
                this.crossesMidnight = true;
            } else {
                this.endDateTime = date.atTime(endTime);
                this.crossesMidnight = false;
            }
        }
    }

    /**
     * Generates a composite volatile ID for event tracking and comparison.
     *
     * @return Composite volatile ID
     */
    private String generateVolatileId() {
        StringBuilder sb = new StringBuilder("WS_");

        if (date != null) {
            sb.append( date ).append("_");
        }

        if (shiftType != null && shiftType.getId() != null) {
            sb.append("ST").append(shiftType.getId()).append("_");
        }

        if (assignedTeams != null && !assignedTeams.isEmpty()) {
            sb.append("T").append(String.join("-", assignedTeams)).append("_");
        }

        if (workScheduleTemplateId != null) {
            sb.append("TPL").append(workScheduleTemplateId).append("_");
        }

        sb.append("C").append(cycleDay);

        return sb.toString();
    }

    // ==================== BUSINESS LOGIC METHODS ====================

    /**
     * Checks if this event overlaps with another event temporally.
     *
     * @param other Other event to check against
     * @return true if events overlap in time
     */
    public boolean overlapsWith(WorkScheduleEvent other) {
        if (other == null || this.startDateTime == null || this.endDateTime == null ||
                other.startDateTime == null || other.endDateTime == null) {
            return false;
        }

        return this.startDateTime.isBefore(other.endDateTime) &&
                this.endDateTime.isAfter(other.startDateTime);
    }

    /**
     * Checks if this event involves the specified team.
     *
     * @param teamName Team name to check
     * @return true if team is assigned to this event
     */
    public boolean hasTeam(String teamName) {
        return assignedTeams != null &&
                assignedTeams.stream().anyMatch(team -> team.equalsIgnoreCase(teamName));
    }

    /**
     * Gets the duration of this event in hours (decimal).
     *
     * @return Duration in hours, or 0 if times unavailable
     */
    public double getDurationHours() {
        if (startDateTime == null || endDateTime == null) {
            return 0.0;
        }

        long minutes = java.time.Duration.between(startDateTime, endDateTime).toMinutes();
        return minutes / 60.0;
    }

    /**
     * Gets the duration of this event in hours (decimal).
     *
     * @return Duration in hours, or 0 if times unavailable
     */
    public double getDurationMinutes() {
        if (startDateTime == null || endDateTime == null) {
            return 0.0;
        }

        return java.time.Duration.between(startDateTime, endDateTime).toMinutes();
    }

    /**
     * Checks if this is a work event (not a rest period).
     *
     * @return true if this is a work event
     */
    public boolean isWorkEvent() {
        return !isRestPeriod && shiftType != null && !shiftType.isRestPeriod();
    }

    /**
     * Creates a display-friendly summary of this event.
     *
     * @return Event summary string
     */
    public String getSummary() {
        StringBuilder summary = new StringBuilder();

        if (title != null) {
            summary.append(title);
        }

        if (startDateTime != null && endDateTime != null) {
            summary.append(" (")
                    .append(startDateTime.toLocalTime())
                    .append("-")
                    .append(endDateTime.toLocalTime());

            if (crossesMidnight) {
                summary.append("+1");
            }

            summary.append(")");
        }

        if (assignedTeams != null && !assignedTeams.isEmpty()) {
            summary.append(" - Teams: ").append(String.join(", ", assignedTeams));
        }

        return summary.toString();
    }

    // ==================== GETTERS AND SETTERS ====================

    public String getVolatileId() { return volatileId; }

    public String getWorkScheduleTemplateId() { return workScheduleTemplateId; }
    public void setWorkScheduleTemplateId(String workScheduleTemplateId) {
        this.workScheduleTemplateId = workScheduleTemplateId;
        this.volatileId = generateVolatileId(); // Regenerate ID
    }

    public int getCycleDay() { return cycleDay; }
    public void setCycleDay(int cycleDay) {
        this.cycleDay = cycleDay;
        this.volatileId = generateVolatileId(); // Regenerate ID
    }

    public LocalDate getDate() { return date; }
    public void setDate(LocalDate date) {
        this.date = date;
        calculateDateTimes();
        this.volatileId = generateVolatileId(); // Regenerate ID
    }

    public LocalDateTime getStartDateTime() { return startDateTime; }
    public LocalDateTime getEndDateTime() { return endDateTime; }

    public boolean crossesMidnight() { return crossesMidnight; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public ShiftType getShiftType() { return shiftType; }
    public void setShiftType(ShiftType shiftType) {
        this.shiftType = shiftType;
        this.isRestPeriod = (shiftType != null && shiftType.isRestPeriod());
        calculateDateTimes();
        this.volatileId = generateVolatileId(); // Regenerate ID
    }

    public List<String> getAssignedTeams() { return new ArrayList<>(assignedTeams); }
    public void setAssignedTeams(List<String> assignedTeams) {
        this.assignedTeams = assignedTeams != null ? new ArrayList<>(assignedTeams) : new ArrayList<>();
        this.volatileId = generateVolatileId(); // Regenerate ID
    }

    public boolean isRestPeriod() { return isRestPeriod; }
    public void setRestPeriod(boolean restPeriod) { this.isRestPeriod = restPeriod; }

    public boolean isOvertime() { return isOvertime; }
    public void setOvertime(boolean overtime) { this.isOvertime = overtime; }

    public String getProviderName() { return providerName; }
    public void setProviderName(String providerName) { this.providerName = providerName; }

    public long getGeneratedTimestamp() { return generatedTimestamp; }

    // ==================== OBJECT METHODS ====================

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        WorkScheduleEvent that = (WorkScheduleEvent) o;

        return Objects.equals(volatileId, that.volatileId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(volatileId);
    }

    @NonNull
    @Override
    public String toString() {
        return "WorkScheduleEvent{" +
                "volatileId='" + volatileId + '\'' +
                ", date=" + date +
                ", title='" + title + '\'' +
                ", shiftType=" + (shiftType != null ? shiftType.getName() : "null") +
                ", teams=" + assignedTeams +
                ", cycleDay=" + cycleDay +
                '}';
    }

    // ==================== BUILDER PATTERN ====================

    /**
     * Builder for creating WorkScheduleEvent instances.
     */
    public static class Builder {
        private WorkScheduleEvent event;

        public Builder() {
            this.event = new WorkScheduleEvent();
        }

        public Builder title(String title) {
            event.setTitle(title);
            return this;
        }

        public Builder date(LocalDate date) {
            event.setDate(date);
            return this;
        }

        public Builder shiftType(ShiftType shiftType) {
            event.setShiftType(shiftType);
            return this;
        }

        public Builder assignedTeams(List<String> teams) {
            event.setAssignedTeams(teams);
            return this;
        }

        public Builder templateId(String templateId) {
            event.setWorkScheduleTemplateId(templateId);
            return this;
        }

        public Builder cycleDay(int cycleDay) {
            event.setCycleDay(cycleDay);
            return this;
        }

        public Builder description(String description) {
            event.setDescription(description);
            return this;
        }

        public Builder providerName(String providerName) {
            event.setProviderName(providerName);
            return this;
        }

        public Builder overtime(boolean isOvertime) {
            event.setOvertime(isOvertime);
            return this;
        }

        public WorkScheduleEvent build() {
            // Regenerate volatile ID with all current data
            event.volatileId = event.generateVolatileId();
            return event;
        }
    }
}